version: '3.7'

services:
  database:
    image: postgres
    container_name: database_poc_arquitetura
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=arquitetura
    volumes:
      - pgdata:/data/postgres

  # redis:
  #   image: redis:alpine
  #   container_name: redis_ignite
  #   ports:
  #     - 6379:6379

  # app:
  #   build: .
  #   container_name: application
  #   ports:
  #     - 3333:3333
  #     - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local
